---
name: repo-testing
on: [push, pull_request]
jobs:
  run-various-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: validate the syntax of python scripts
        run: |
          python -m py_compile $(git ls-files '*.py')
    #  - name: run pylint
    #    run: |
    #      pylint --max-line-length=130 $(git ls-files '*.py')
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
          file_or_dir: .
      - name: run pytest
        run: py.test -vv
      - name: report pytest code coverage
        run: py.test --cov .
